#ifndef SERIAL_PROTOCOLS_UTILS_H
#define SERIAL_PROTOCOLS_UTILS_H

#include <stdint.h>

#define NUM_MOTORS 4

#define START_BYTE 0xAA
#define END_BYTE   0xBB
#define MSG_FEEDBACK 0x01
#define FEEDBACK_PAYLOAD_LENGTH 8 // 2 floats
#define FEEDBACK_PACKET_SIZE 13 // 1 + 1 + 1 + FEEDBACK_PAYLOAD_LENGTH + 1 + 1

#define MSG_JOINT_COMMAND 0x02
#define JOINT_COMMAND_PAYLOAD_LENGTH 8 // 2 floats
#define JOINT_COMMAND_PACKET_SIZE 13 // 1 + 1 + 1 + JOINT_COMMAND_PAYLOAD_LENGTH + 1 + 1

#endif
